### ISSUE TITLE
Supprimer la nécessité de définir la variable d'environnement RAILS_MASTER_KEY

### ISSUE THREAD

**Issue by yannski** [betagouv/civilsdeladefense#614]
```
       ActiveSupport::MessageEncryptor::InvalidMessage: ActiveSupport::MessageEncryptor::InvalidMessage
       /build/a518c1cb-ca7e-4894-96c0-88acb0b51597/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/message_encryptor.rb:206:in `rescue in _decrypt'
       /build/a518c1cb-ca7e-4894-96c0-88acb0b51597/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/message_encryptor.rb:183:in `_decrypt'
       /build/a518c1cb-ca7e-4894-96c0-88acb0b51597/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/message_encryptor.rb:157:in `decrypt_and_verify'
       /build/a518c1cb-ca7e-4894-96c0-88acb0b51597/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/messages/rotator.rb:21:in `decrypt_and_verify'
       /build/a518c1cb-ca7e-4894-96c0-88acb0b51597/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/encrypted_file.rb:80:in `decrypt'
       /build/a518c1cb-ca7e-4894-96c0-88acb0b51597/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/encrypted_file.rb:43:in `read'
       /build/a518c1cb-ca7e-4894-96c0-88acb0b51597/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/encrypted_configuration.rb:21:in `read'
       /build/a518c1cb-ca7e-4894-96c0-88acb0b51597/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/encrypted_configuration.rb:33:in `config'
```

**Comment by Grainedepaillette** [comment]
@btrd Penses-tu que ce ticket est toujours d'actualité ? Merci.
