### ISSUE TITLE
Installation problème

### ISSUE THREAD

**Issue by sisitototest** [betagouv/civilsdeladefense#812]
Bonjour,

J'ai bien ajouté la variable SMTP_URL. Bon fonctionnement jusqu'à l'erreur ci-dessous:
Merci beaucoup pour votre aide
Bonne journée
Anne-Laure SIMON

      [4/4] Building fresh packages...
       Done in 22.23s.
       rake aborted!
       TypeError: no implicit conversion of nil into String
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/config/environments/production.rb:77:in `unescape'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/config/environments/production.rb:77:in `block in <top (required)>'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/railtie.rb:234:in `instance_eval'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/railtie.rb:234:in `configure'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/config/environments/production.rb:5:in `<top (required)>'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/engine.rb:571:in `block (2 levels) in <class:Engine>'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/engine.rb:570:in `each'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/engine.rb:570:in `block in <class:Engine>'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/initializable.rb:32:in `instance_exec'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/initializable.rb:32:in `run'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/initializable.rb:50:in `each'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/initializable.rb:50:in `tsort_each_child'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/initializable.rb:60:in `run_initializers'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/application.rb:384:in `initialize!'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/config/environment.rb:7:in `<top (required)>'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/application.rb:360:in `require_environment!'
       /build/44ac8402-d4ff-4a9a-ae61-116046930671/vendor/bundle/ruby/2.7.0/gems/railties-6.1.1/lib/rails/application.rb:526:in `block in run_tasks_blocks'
       Tasks: TOP => assets:precompile => webpacker:compile => environment
       (See full trace by running task with --trace)

 !
 !     Precompiling assets failed.
 !
 !     An error occured during buildpack compilation
 !   Error deploying the application
 !   → Invalid return code from buildpack

**Comment by btrd** [comment]
Le format de `SMTP_URL` doit correspondre à ça `smtp://username:password@hostname:port`

**Comment by sisitototest** [comment]
la build a fonctionné par contre

Using release configuration from last framework (Ruby).
-----> Procfile declares types -> web, clock, postdeploy
-----> .slugignore detected, cleaning project before packaging
 !     'doc': No such file or directory
       '/tmp/cache' has been removed from the image
       '/node_modules' has been removed from the image
       '/.cache/yarn' has been removed from the image
 Build complete, shipping your container...
 Waiting for your application to boot... 
 !   Error deploying the application
 !   → Your application has stopped unexpectedly with the following output:

======== BEGIN OUTPUT ========
2021-02-12 15:09:51.866858434 +0000 UTC [web-1] => Booting Puma
2021-02-12 15:09:51.866892773 +0000 UTC [web-1] => Rails 6.0.3.4 application starting in production
2021-02-12 15:09:51.866894881 +0000 UTC [web-1] => Run `rails server --help` for more startup options
2021-02-12 15:09:51.930322190 +0000 UTC [web-1] Exiting
2021-02-12 15:09:51.930327771 +0000 UTC [web-1] /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/connection_specification.rb:162:in `spec': database configuration does not specify adapter (ActiveRecord::AdapterNotSpecified)
2021-02-12 15:09:51.930364414 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:1052:in `establish_connection'
2021-02-12 15:09:51.930426702 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_handling.rb:51:in `establish_connection'
2021-02-12 15:09:51.930428543 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/railtie.rb:201:in `block (2 levels) in <class:Railtie>'
2021-02-12 15:09:51.930444836 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
2021-02-12 15:09:51.930473955 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
2021-02-12 15:09:51.930474885 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
2021-02-12 15:09:51.930560027 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
2021-02-12 15:09:51.930561262 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
2021-02-12 15:09:51.930562062 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:42:in `each'
2021-02-12 15:09:51.930562829 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
2021-02-12 15:09:51.930563706 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/railtie.rb:198:in `block in <class:Railtie>'
2021-02-12 15:09:51.930564592 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
2021-02-12 15:09:51.930588376 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
2021-02-12 15:09:51.930589270 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
2021-02-12 15:09:51.930644549 +0000 UTC [web-1] 	from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
2021-02-12 15:09:51.930645618 +0000 UTC [web-1] 	from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2021-02-12 15:09:51.930708912 +0000 UTC [web-1] 	from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
2021-02-12 15:09:51.930712041 +0000 UTC [web-1] 	from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
2021-02-12 15:09:51.930755304 +0000 UTC [web-1] 	from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
2021-02-12 15:09:51.930757001 +0000 UTC [web-1] 	from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
2021-02-12 15:09:51.930884083 +0000 UTC [web-1] 	from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
2021-02-12 15:09:51.930897940 +0000 UTC [web-1] 	from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
2021-02-12 15:09:51.930911219 +0000 UTC [web-1] 	from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
2021-02-12 15:09:51.930979330 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
2021-02-12 15:09:51.930981916 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
2021-02-12 15:09:51.931001442 +0000 UTC [web-1] 	from /app/config/environment.rb:7:in `<top (required)>'
2021-02-12 15:09:51.931046338 +0000 UTC [web-1] 	from config.ru:5:in `require_relative'
2021-02-12 15:09:51.931047691 +0000 UTC [web-1] 	from config.ru:5:in `block in <main>'
2021-02-12 15:09:51.931088766 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
2021-02-12 15:09:51.931091181 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
2021-02-12 15:09:51.931107221 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
2021-02-12 15:09:51.931108062 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
2021-02-12 15:09:51.931121857 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
2021-02-12 15:09:51.931151498 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
2021-02-12 15:09:51.931153682 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
2021-02-12 15:09:51.931172668 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
2021-02-12 15:09:51.931215466 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
2021-02-12 15:09:51.931216854 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
2021-02-12 15:09:51.931262652 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:39:in `start'
2021-02-12 15:09:51.931264466 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:147:in `block in perform'
2021-02-12 15:09:51.931343281 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `tap'
2021-02-12 15:09:51.931350640 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `perform'
2021-02-12 15:09:51.931352282 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
2021-02-12 15:09:51.931353295 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
2021-02-12 15:09:51.931423113 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
2021-02-12 15:09:51.931426856 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
2021-02-12 15:09:51.931428106 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
2021-02-12 15:09:51.931429138 +0000 UTC [web-1] 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<top (required)>'
2021-02-12 15:09:51.931430189 +0000 UTC [web-1] 	from bin/rails:4:in `require'
2021-02-12 15:09:51.931432457 +0000 UTC [web-1] 	from bin/rails:4:in `<main>'
======== END OUTPUT ========

 !   Read the output and fix your code accordingly
 !   Common errors:       http://doc.scalingo.com/deployment/start-error#crashed
 !   Need help? Email us: support@scalingo.com

**Comment by btrd** [comment]
Est-ce que vous avez bien créé un addon postgreSQL ?

**Comment by sisitototest** [comment]
Bonjour,
Effectivement après l'ajout d'un addon postgres le premier deploiement fonctionne.
En revanche conformémemt à la documentation j'ai supprimé la variable DO_NOT_POSTDEPLOY au deuxieme deploiement.
Peux tu m'indiquer comment lancer les commandes ci-dessous?
Merci beaucoup pour ton aide
Bonne journée

__Lancer le déploiement puis charger le schéma de données :

rails db:schema:load

Supprimer la variable d'environnement DO_NOT_POSTDEPLOY.

Créer la première organisation :

hsh = {
  name: 'Civils de la Défense',
  name_business_owner: 'le Ministère des Armées',
  subdomain: 'XXX',
  domain: 'XXX.YYY.ZZZ'
}
organization = Organization.create!(hsh)

Créer le premier compte admin :

bant_admin = Administrator.new email: 'prenom.nom@domaine.com',
                               first_name: 'Prénom',
                               last_name: 'Nom',
                               password: 'xxxxxxxxxx',
                               password_confirmation: 'xxxxxxxxxx',
                               very_first_account: true,
                               role: 'bant',
                               organization: organization
bant_admin.skip_confirmation_notification!
bant_admin.save!
bant_admin.confirm

Créer la première page :

root_page = organization.pages.create!({
  title: 'Plateforme de recrutement de personnel civils contractuels pour le Ministère des Armées',
  only_link: false
})__


Voici le message d'erreur en fin de 2eme deploiement après suppression de la variable  DO_NOT_POSTDEPLOY.



2021-02-22 12:55:52.544883739 +0100 CET [postdeploy-7075] /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:828:in `exec_migration'
2021-02-22 12:55:53.535876813 +0100 CET [manager] container [postdeploy-7075] (60339bc26ffbd9564ba006bc) has stopped with exit code: 1
 !   Error deploying the application
 !   → Postdeploy hook failed with status '1'
 !   Documentation:	http://doc.scalingo.com/deployment/start-error#postdeploy

**Comment by sisitototest** [comment]
Le deuxième déploiement est finalement en succès.
Le chargement du schéma de la BDD est OK.

Par contre la commande ci-dessous ne fonctionne pas.
scalingo -a my-app run bundle exec rails hsh = {
  name: 'Civils de la Défense',
  business_owner_name: 'le Ministère des Armées',
  subdomain: 'XXX',
  domain: 'XXX.YYY.ZZZ'
}
organization = Organization.create!(hsh)

Merci beaucoup pour ton aide

**Comment by odurgeau** [comment]
Bonjour, 
J'ai réussi à créer l'organisation avec le code suivant : 

```
hsh = {
  service_name: 'Civils de la Défense',
  brand_name: 'le Ministère des Armées',
  subdomain: 'XXX',
  domain: 'XXX.YYY.ZZZ',
  prefix_article: 'mna'
}
organization = Organization.create!(hsh)
```

Et pour la gestion des mails, il manquait ça pour ma part :
```
DEFAULT_FROM=username@host
```

Et quand on voit `username_url_encoded@smtp_host`, c'est parce qu'il faut encoder le mail et le remplacer, comme par exemple olivier@civilsdeladefense.com -> `olivier%40civilsdeladefense.com`, ce qui donne :
```
SMTP_URL=smtp://olivier%40civilsdeladefense.com:password@host:port
```

**Comment by btrd** [comment]
@odurgeau Merci pour ta réponse, on a réussi à faire le déploiement avec @sisitototest :)
